### PR TITLE
Add hubsite configuration for Navidrome

### PR DESCRIPTION
**Pull request by Kuchenmampfer**
I noticed that Navidrome is missing on my hubsite.

This change does not fix that for me, but I think it is part of the fix and I could not find any other obvious thing. So I hope you can point me to what else needs to be changed or add it to this PR yourself?

### CODE REVIEW

**Comment by spantaleev** [comment]
Thanks!

Other required parts are:

- actually injecting these new variables into `mash_playbook_hubsite_service_list_auto_itemized` in `templates/group_vars_mash_servers` ( a bit below)
- adding the Navidrome logo (`navidrome.png`) to the [Hubsite role](https://github.com/mother-of-all-self-hosting/ansible-role-hubsite), under `assets/` - a separate PR

**Comment by Kuchenmampfer** [comment]
Thanks for the pointer :)

I have injected the variables and the logo was already available. So I think this should be ready now.

However, when I tested it, I got a 404 error until I restarted the `mash-hubsite` container manually. I have no idea what causes this as all the html and css files were present and I could not get logs from that container. So maybe you want to test for this yourself before merging I guess...

**Comment by spantaleev** [comment]
I suppose Hubsite needs to be reinstalled and restarted as well before these logo changes can take effect.

--------

I think we're still missing a PR to the Hubsite role before merging this.

**Comment by Kuchenmampfer** [comment]
no, that role already has the logo

**Comment by spantaleev** [comment]
Oh, you're right! Merged now! Thanks! :bow:

**Pull request merged**
